name: Update Training Data in Chatbot Platform (e.g. CAI)

on:
  push:
    branches: [ main, master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: read file
        id: read_md_file
        run: |
          repo="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/blob/${GITHUB_REF#refs/heads/}"
          files=$(git diff --name-only HEAD HEAD~1 | grep ".*docs/faq.md$")
          
          file_output=0
          
          for file in $files;do
            echo "processing $file"
            file_output=$(cat $file)
            echo "$file_output"
            echo "::set-output name=md_file::$(awk '{printf "%s\\n", $0}' "$file")"
          done
          
          deno run --allow-net --allow-env src/gh-action-proxy/transform-and-update.ts "$file_output" ${{ secrets.USER_NAME}} ${{ secrets.BOT_NAME }} ${{ secrets.BOT_VERSION}} ${{ secrets.KNOWLEDGE_SOURCE_NAME}} ${{ secrets.X_TOKEN}} ${{ secrets.AUTH_URL}} ${{ secrets.CLIENT_ID}} ${{ secrets.CLIENT_SECRET}}
